

export const UPLOAD_VISITPHOTOS_REQUEST = 'UPLOAD_VISITPHOTOS_REQUEST'
export const UPLOAD_VISITPHOTOS_SUCCESS = 'UPLOAD_VISITPHOTOS_SUCCESS'
export const UPLOAD_VISITPHOTOS_FAIL = 'UPLOAD_VISITPHOTOS_FAIL'

export const UPLOAD_VISITFORM_REQUEST = 'UPLOAD_VISITFORM_REQUEST'
export const UPLOAD_VISITFORM_SUCCESS = 'UPLOAD_VISITFORM_SUCCESS'
export const UPLOAD_VISITFORM_FAIL = 'UPLOAD_VISITFORM_FAIL'

export const UPLOAD_APPLIEDFORM_REQUEST = 'UPLOAD_APPLIEDFORM_REQUEST'
export const UPLOAD_APPLIEDFORM_SUCCESS = 'UPLOAD_APPLIEDFORM_SUCCESS'
export const UPLOAD_APPLIEDFORM_FAIL = 'UPLOAD_APPLIEDFORM_FAIL'