

export const UPLOAD_VISITPHOTOS_REQUEST = 'UPLOAD_VISITPHOTOS_REQUEST'
export const UPLOAD_VISITPHOTOS_SUCCESS = 'UPLOAD_VISITPHOTOS_SUCCESS'
export const UPLOAD_VISITPHOTOS_FAIL = 'UPLOAD_VISITPHOTOS_FAIL'

export const UPLOAD_VISITFORM_REQUEST = 'UPLOAD_VISITFORM_REQUEST'
export const UPLOAD_VISITFORM_SUCCESS = 'UPLOAD_VISITFORM_SUCCESS'
export const UPLOAD_VISITFORM_FAIL = 'UPLOAD_VISITFORM_FAIL'

export const UPLOAD_APPLIEDFORM_REQUEST = 'UPLOAD_APPLIEDFORM_REQUEST'
export const UPLOAD_APPLIEDFORM_SUCCESS = 'UPLOAD_APPLIEDFORM_SUCCESS'
export const UPLOAD_APPLIEDFORM_FAIL = 'UPLOAD_APPLIEDFORM_FAIL'


export const CASE_NO_GENERATE_REQUEST = 'CASE_NO_GENERATE_REQUEST'
export const CASE_NO_GENERATE_SUCCESS = 'CASE_NO_GENERATE_SUCCESS'
export const CASE_NO_GENERATE_FAIL = 'CASE_NO_GENERATE_FAIL'


export const CASE_FILES_LIST_REQUEST = 'CASE_FILES_LIST_REQUEST'
export const CASE_FILES_LIST_SUCCESS = 'CASE_FILES_LIST_SUCCESS'
export const CASE_FILES_LIST_FAIL = 'CASE_FILES_LIST_FAIL'

export const CASE_FILES_DELETE_REQUEST = 'CASE_FILES_DELETE_REQUEST'
export const CASE_FILES_DELETE_SUCCESS = 'CASE_FILES_DELETE_SUCCESS'
export const CASE_FILES_DELETE_FAIL = 'CASE_FILES_DELETE_FAIL'

export const CASE_ADD_REQUEST = 'CASE_ADD_REQUEST'
export const CASE_ADD_SUCCESS = 'CASE_ADD_SUCCESS'
export const CASE_ADD_FAIL = 'CASE_ADD_FAIL'