export const FINANCE_LIST_REQUEST = 'FINANCE_LIST_REQUEST'
export const FINANCE_LIST_SUCCESS = 'FINANCE_LIST_SUCCESS'
export const FINANCE_LIST_FAIL = 'FINANCE_LIST_FAIL'

export const INCOME_LIST_REQUEST = 'INCOME_LIST_REQUEST'
export const INCOME_LIST_SUCCESS = 'INCOME_LIST_SUCCESS'
export const INCOME_LIST_FAIL = 'INCOME_LIST_FAIL'

export const INCOME_SUM_REQUEST = 'INCOME_SUM_REQUEST'
export const INCOME_SUM_SUCCESS = 'INCOME_SUM_SUCCESS'
export const INCOME_SUM_FAIL = 'INCOME_SUM_FAIL'

export const OUTCOME_SUM_REQUEST = 'OUTCOME_SUM_REQUEST'
export const OUTCOME_SUM_SUCCESS = 'OUTCOME_SUM_SUCCESS'
export const OUTCOME_SUM_FAIL = 'OUTCOME_SUM_FAIL'

export const OUTCOME_LIST_REQUEST = 'OUTCOME_LIST_REQUEST'
export const OUTCOME_LIST_SUCCESS = 'OUTCOME_LIST_SUCCESS'
export const OUTCOME_LIST_FAIL = 'OUTCOME_LIST_FAIL'

export const INCOME_ADD_REQUEST = 'INCOME_ADD_REQUEST'
export const INCOME_ADD_SUCCESS = 'INCOME_ADD_SUCCESS'
export const INCOME_ADD_FAIL = 'INCOME_ADD_FAIL'

export const OUTCOME_ADD_REQUEST = 'OUTCOME_ADD_REQUEST'
export const OUTCOME_ADD_SUCCESS = 'OUTCOME_ADD_SUCCESS'
export const OUTCOME_ADD_FAIL = 'OUTCOME_ADD_FAIL'

export const INCOME_UPDATE_REQUEST = 'INCOME_UPDATE_REQUEST'
export const INCOME_UPDATE_SUCCESS = 'INCOME_UPDATE_SUCCESS'
export const INCOME_UPDATE_FAIL = 'INCOME_UPDATE_FAIL'

export const OUTCOME_UPDATE_REQUEST = 'OUTCOME_UPDATE_REQUEST'
export const OUTCOME_UPDATE_SUCCESS = 'OUTCOME_UPDATE_SUCCESS'
export const OUTCOME_UPDATE_FAIL = 'OUTCOME_UPDATE_FAIL'

export const INCOME_DETAIL_REQUEST = 'INCOME_DETAIL_REQUEST'
export const INCOME_DETAIL_SUCCESS = 'INCOME_DETAIL_SUCCESS'
export const INCOME_DETAIL_FAIL = 'INCOME_DETAIL_FAIL'

export const OUTCOME_DETAIL_REQUEST = 'OUTCOME_DETAIL_REQUEST'
export const OUTCOME_DETAIL_SUCCESS = 'OUTCOME_DETAIL_SUCCESS'
export const OUTCOME_DETAIL_FAIL = 'OUTCOME_DETAIL_FAIL'

export const INCOME_UPDATE_RESET = 'INCOME_UPDATE_RESET'
export const OUTCOME_UPDATE_RESET = 'OUTCOME_UPDATE_RESET'

export const INCOME_DELETE_REQUEST = 'INCOME_DELETE_REQUEST'
export const INCOME_DELETE_SUCCESS = 'INCOME_DELETE_SUCCESS'
export const INCOME_DELETE_FAIL = 'INCOME_DELETE_FAIL'

export const OUTCOME_DELETE_REQUEST = 'OUTCOME_DELETE_REQUEST'
export const OUTCOME_DELETE_SUCCESS = 'OUTCOME_DELETE_SUCCESS'
export const OUTCOME_DELETE_FAIL = 'OUTCOME_DELETE_FAIL'


export const OUTCOME_ADD_ITEM = 'OUTCOME_ADD_ITEM'
export const OUTCOME_REMOVE_ITEM = 'OUTCOME_REMOVE_ITEM'