export const MEMBERS_LIST_REQUEST = 'MEMBERS_LIST_REQUEST'
export const MEMBERS_LIST_SUCCESS = 'MEMBERS_LIST_SUCCESS'
export const MEMBERS_LIST_FAIL = 'MEMBERS_LIST_FAIL'


export const MEMBER_ADD_REQUEST = 'MEMBER_ADD_REQUEST'
export const MEMBER_ADD_SUCCESS = 'MEMBER_ADD_SUCCESS'
export const MEMBER_ADD_FAIL = 'MEMBER_ADD_FAIL'

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST'
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS'
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL'


export const MEMBER_DETAIL_REQUEST = 'MEMBER_DETAIL_REQUEST'
export const MEMBER_DETAIL_SUCCESS = 'MEMBER_DETAIL_SUCCESS'
export const MEMBER_DETAIL_FAIL = 'MEMBER_DETAIL_FAIL'

export const MEMBER_UPDATE_RESET = 'MEMBER_UPDATE_RESET'

export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST'
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS'
export const MEMBER_DELETE_FAIL = 'MEMBER_DELETE_FAIL'