export const SCHOOLS_LIST_REQUEST = 'SCHOOLS_LIST_REQUEST'
export const SCHOOLS_LIST_SUCCESS = 'SCHOOLS_LIST_SUCCESS'
export const SCHOOLS_LIST_FAIL = 'SCHOOLS_LIST_FAIL'

export const SCHOOL_REQUEST = 'SCHOOL_REQUEST'
export const SCHOOL_REQUEST_SUCCESS = 'SCHOOL_REQUEST_SUCCESS'
export const SCHOOL_REQUEST_FAIL = 'SCHOOL_REQUEST_FAIL'

export const SCHOOL_ADD_REQUEST = 'SCHOOL_ADD_REQUEST'
export const SCHOOL_ADD_SUCCESS = 'SCHOOL_ADD_SUCCESS'
export const SCHOOL_ADD_FAIL = 'SCHOOL_ADD_FAIL'

export const SCHOOL_UPDATE_REQUEST = 'SCHOOL_UPDATE_REQUEST'
export const SCHOOL_UPDATE_SUCCESS = 'SCHOOL_UPDATE_SUCCESS'
export const SCHOOL_UPDATE_FAIL = 'SCHOOL_UPDATE_FAIL'


