export const SCHOLARSHIP_LIST_REQUEST = 'SCHOLARSHIP_LIST_REQUEST'
export const SCHOLARSHIP_LIST_SUCCESS = 'SCHOLARSHIP_LIST_SUCCESS'
export const SCHOLARSHIP_LIST_FAIL = 'SCHOLARSHIP_LIST_FAIL'


export const SCHOLARSHIP_ADD_REQUEST = 'SCHOLARSHIP_ADD_REQUEST'
export const SCHOLARSHIP_ADD_SUCCESS = 'SCHOLARSHIP_ADD_SUCCESS'
export const SCHOLARSHIP_ADD_FAIL = 'SCHOLARSHIP_ADD_FAIL'

export const SCHOLARSHIP_UPDATE_REQUEST = 'SCHOLARSHIP_UPDATE_REQUEST'
export const SCHOLARSHIP_UPDATE_SUCCESS = 'SCHOLARSHIP_UPDATE_SUCCESS'
export const SCHOLARSHIP_UPDATE_FAIL = 'SCHOLARSHIP_UPDATE_FAIL'


export const SCHOLARSHIP_DETAIL_REQUEST = 'SCHOLARSHIP_DETAIL_REQUEST'
export const SCHOLARSHIP_DETAIL_SUCCESS = 'SCHOLARSHIP_DETAIL_SUCCESS'
export const SCHOLARSHIP_DETAIL_FAIL = 'SCHOLARSHIP_DETAIL_FAIL'

export const SCHOLARSHIP_UPDATE_RESET = 'SCHOLARSHIP_UPDATE_RESET'

export const SCHOLARSHIP_DELETE_REQUEST = 'SCHOLARSHIP_DELETE_REQUEST'
export const SCHOLARSHIP_DELETE_SUCCESS = 'SCHOLARSHIP_DELETE_SUCCESS'
export const SCHOLARSHIP_DELETE_FAIL = 'SCHOLARSHIP_DELETE_FAIL'