export const SEMESTERS_LIST_REQUEST = 'SEMESTERS_LIST_REQUEST'
export const SEMESTERS_LIST_SUCCESS = 'SEMESTERS_LIST_SUCCESS'
export const SEMESTERS_LIST_FAIL = 'SEMESTERS_LIST_FAIL'


export const SEMESTER_ADD_REQUEST = 'SEMESTER_ADD_REQUEST'
export const SEMESTER_ADD_SUCCESS = 'SEMESTER_ADD_SUCCESS'
export const SEMESTER_ADD_FAIL = 'SEMESTER_ADD_FAIL'

export const SEMESTER_UPDATE_REQUEST = 'SEMESTER_UPDATE_REQUEST'
export const SEMESTER_UPDATE_SUCCESS = 'SEMESTER_UPDATE_SUCCESS'
export const SEMESTER_UPDATE_FAIL = 'SEMESTER_UPDATE_FAIL'


export const SEMESTER_DETAIL_REQUEST = 'SEMESTER_DETAIL_REQUEST'
export const SEMESTER_DETAIL_SUCCESS = 'SEMESTER_DETAIL_SUCCESS'
export const SEMESTER_DETAIL_FAIL = 'SEMESTER_DETAIL_FAIL'

export const SEMESTER_UPDATE_RESET = 'SEMESTER_UPDATE_RESET'

export const SEMESTER_DELETE_REQUEST = 'SEMESTER_DELETE_REQUEST'
export const SEMESTER_DELETE_SUCCESS = 'SEMESTER_DELETE_SUCCESS'
export const SEMESTER_DELETE_FAIL = 'SEMESTER_DELETE_FAIL'