export const STUDENTS_LIST_REQUEST = 'STUDENTS_LIST_REQUEST'
export const STUDENTS_LIST_SUCCESS = 'STUDENTS_LIST_SUCCESS'
export const STUDENTS_LIST_FAIL = 'STUDENTS_LIST_FAIL'


export const STUDENT_ADD_REQUEST = 'STUDENT_ADD_REQUEST'
export const STUDENT_ADD_SUCCESS = 'STUDENT_ADD_SUCCESS'
export const STUDENT_ADD_FAIL = 'STUDENT_ADD_FAIL'

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL'


export const STUDENT_DETAIL_REQUEST = 'STUDENT_DETAIL_REQUEST'
export const STUDENT_DETAIL_SUCCESS = 'STUDENT_DETAIL_SUCCESS'
export const STUDENT_DETAIL_FAIL = 'STUDENT_DETAIL_FAIL'

export const STUDENT_UPDATE_RESET = 'STUDENT_UPDATE_RESET'

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST'
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS'
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL'