# Generated by Django 3.2.4 on 2021-07-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='id_num',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='member',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_family_User', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='intro_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_family_Intro', to='base.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
