# Generated by Django 3.2.4 on 2021-07-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20210724_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributeContext',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='case',
            old_name='context',
            new_name='case_no',
        ),
        migrations.RemoveField(
            model_name='case',
            name='file',
        ),
        migrations.AddField(
            model_name='case',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studnet_case', to='base.student'),
        ),
        migrations.AlterField(
            model_name='case',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_case', to='base.school'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finance',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_case', to='base.case'),
        ),
        migrations.CreateModel(
            name='ContributeItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribute_context', to='base.contributecontext')),
                ('student_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribute_studnet', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='CaseData',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caseName_caseData', to='base.case')),
            ],
        ),
    ]
