# Generated by Django 3.2.4 on 2021-07-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210727_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_end',
        ),
        migrations.RemoveField(
            model_name='case',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='case',
            name='school',
        ),
    ]
