# Generated by Django 3.2.4 on 2021-07-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210727_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_case', to='base.student'),
        ),
    ]
