# Generated by Django 3.2.4 on 2021-07-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_case_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InCome',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('income_money', models.IntegerField(blank=True, default=0, null=True)),
                ('unit', models.CharField(default='NTD', max_length=200)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyCategory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OutCome',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('outcome_money', models.IntegerField(blank=True, default=0, null=True)),
                ('unit', models.CharField(default='NTD', max_length=200)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_category', to='base.moneycategory')),
                ('confirmed_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_outcome', to='base.member')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_contribute_context', to='base.contributecontext')),
                ('to_whom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_to_whom', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contributeitem',
            name='month',
        ),
        migrations.RemoveField(
            model_name='scholorship',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='scholorship',
            name='end_date',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_category', to='base.moneycategory'),
        ),
        migrations.AddField(
            model_name='income',
            name='confirmed_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_income', to='base.member'),
        ),
        migrations.AddField(
            model_name='income',
            name='from_whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_from_whom', to='base.student'),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contribute_context', to='base.contributecontext'),
        ),
        migrations.AddField(
            model_name='contributeitem',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribute_item_semester', to='base.semester'),
        ),
        migrations.AddField(
            model_name='scholorship',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_scholorship', to='base.semester'),
        ),
    ]
