# Generated by Django 3.2.4 on 2021-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210730_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
