# Generated by Django 3.2.4 on 2021-08-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_income_from_whom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ('-created_at',)},
        ),
    ]
