# Generated by Django 3.2.4 on 2021-08-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210804_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeContributeItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeContributeContext',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeContributeItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_contribute_context', to='base.outcomecontributecontext')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_contribute_item_semester', to='base.semester')),
                ('student_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_contribute_studnet', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeMoneyCategory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='MoneyCategory',
            new_name='IncomeMoneyCategory',
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_income_contribute_context', to='base.contributecontext'),
        ),
        migrations.RenameModel(
            old_name='ContributeContext',
            new_name='IncomeContributeContext',
        ),
        migrations.DeleteModel(
            name='ContributeItem',
        ),
        migrations.AddField(
            model_name='incomecontributeitem',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contribute_context', to='base.incomecontributecontext'),
        ),
        migrations.AddField(
            model_name='incomecontributeitem',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contribute_item_semester', to='base.semester'),
        ),
        migrations.AddField(
            model_name='incomecontributeitem',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contribute_studnet', to='base.student'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_category', to='base.outcomemoneycategory'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_outcome_contribute_context', to='base.outcomecontributecontext'),
        ),
    ]
