# Generated by Django 3.2.4 on 2021-08-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210804_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
