# Generated by Django 3.2.4 on 2021-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210812_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholorshipWithOutcomeRelation',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('scholorship_id', models.IntegerField(blank=True, max_length=200, null=True)),
                ('outcome_id', models.IntegerField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
