# Generated by Django 3.2.4 on 2021-08-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_scholorshipwithoutcomerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_scholarship', to='base.semester')),
            ],
        ),
        migrations.RenameModel(
            old_name='ScholorshipWithOutcomeRelation',
            new_name='ScholarshipWithOutcomeRelation',
        ),
        migrations.RenameField(
            model_name='scholarshipwithoutcomerelation',
            old_name='scholorship_id',
            new_name='scholarship_id',
        ),
        migrations.DeleteModel(
            name='Scholorship',
        ),
    ]
