# Generated by Django 3.2.4 on 2021-08-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210813_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applied_form_photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_form_photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
