# Generated by Django 3.2.4 on 2021-08-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210818_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgdata',
            old_name='url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='data',
            name='url',
        ),
        migrations.AddField(
            model_name='data',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='memo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='orgdata',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orgdata',
            name='type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='StudentsPhotoLink',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('photo_name', models.CharField(blank=True, max_length=512, null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(blank=True, max_length=512, null=True)),
                ('memo', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student')),
            ],
        ),
    ]
